version: '3.8'

services:
  groot_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: groot_telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./credentials:/app/credentials
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
